### ISSUE TITLE
DSC Panel Support?

### ISSUE THREAD

**Issue by kars85** [TD22057/ad-mqtt#15]
Hello,

Some observations - I had to cast the serial_number as a string, as DSC ESN/serials are alphanumeric in a couple spots.

1) In Bridge.py and Devices.py - [Here are the changes](https://github.com/rgriffogoes/ad-mqtt/commit/512405c26fb95578e7feffd1a97ee7792ced43e9)

Debug output shows connectivity to the Alarm Decoder appliance, but none of the sensors populate.

**Comment by TD22057** [comment]
str->int is easy enough to merge and shouldn't cause any problems.  I have an ademco panel so I can't help much w/ DSC.  

Not sure what you mean by "populate".  If you mean none of the updates from the AD show up, then it's something in the way the AD software is talking to this library.  That setup happens here: https://github.com/TD22057/ad-mqtt/blob/main/ad_mqtt/run.py#L42-L44 and also the Bridge class talks w/ the AD code.  If you want to dig, go into the AD library and add logging/print statements in this class https://github.com/nutechsoftware/alarmdecoder/blob/d392edb87272c18dbcd3259aad90135cf354a86c/alarmdecoder/decoder.py#L27 to see what messages are showing up and what happens to them.   You might try searching DSC in the alarmdecoder code and see if anything pops up that looks like it might cause this.

**Comment by kars85** [comment]
@TD22057 - thank you so much for responding. Appreciate you pointing to the relevant scripts.

I've got a python script "importer" I'm bringing into your project for sensor discovery setup as such...

![2024-03-07_19h14_34](https://github.com/TD22057/ad-mqtt/assets/6616548/03c7c562-2ee7-44ba-ae8e-9ee416b705c3)

So like I said, the panel from AD works over MQTT, but no actual sensors pull from AD. Strange, and not understanding the communication flow completely due to my lack of python knowledge, am trying to understand any deltas between DSC/Ademco/Honeywell causing this to not work.

**Comment by TD22057** [comment]
Are you sure you should have a leading space in the serial number?  I'd check that vs what's reported first.

I don't know what you mean by "no sensors pull from AD".  Please just describe the problem.  Do mqtt messages go out?  Do sensor values not get updated?  

You should also be enable debug level logging (`cfg.log.level = logging.DEBUG`) and check the log files.  It will tell you what my software sees and what it does with it.

**Comment by kars85** [comment]
I'm running a forked version of your codebase. Basically it's everything you've built, with some overhead to be able to be built into a docker image.

[Fork](https://github.com/rgriffogoes/ad-mqtt)

I'll try taking the leading space off. but all that I get via MQTT is the topic, no actual values for the sensor.

![2024-03-07_19h57_55](https://github.com/TD22057/ad-mqtt/assets/6616548/281c7284-0c7e-4933-aec5-676ca97f9a4a)

![2024-03-07_19h56_36](https://github.com/TD22057/ad-mqtt/assets/6616548/d5cd4988-dd94-4a8c-a27c-e3bb41987509)

![2024-03-07_19h59_17](https://github.com/TD22057/ad-mqtt/assets/6616548/29362524-d9f5-479f-a1fe-e1f3422757dd)

I don't know if you are interested, but here is my docker compose for what was forked from you:

```
  ad-mqtt:
    image: rgriffogoes/ad-mqtt:latest
    #image: rgriffogoes/ad-mqtt:cc5680dd7195
    container_name: ad-mqtt
    environment:
    - ADMQTT_SOCKET_HOST=10.10.100.30
    - ADMQTT_MQTT_HOST=10.10.100.3
    - ADMQTT_LOG_LEVEL=DEBUG
    - ADMQTT_ALARM_CODE=*85555 #what is this for?
    volumes:
    - ${DOCKERCONFDIR}/ad-mqtt-data/devices.py:/home/devices.py
    restart: unless-stopped
```
